name: 'CMake build, run unit tests with Googletest and run e2e test'

on:
  push:
    branches:
    - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            g++ \
            libopencv-dev \
            libomp-dev

      - name: Check OpenCV
        run: pkg-config --modversion opencv4

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DOpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4

      - name: Build
        run: cmake --build build --config Release

      - name: Run unit tests
        run: ./build/unit_tests

      - name: Write shrinking kernel test input file
        run: |
          for ((i = 1 ; i <= 10 ; i++)); do
          tee -a ./build/e2e_test.txt <<EOF
          $(pwd)/datasets/airplane/shrinking_kernel/$i.png
          EOF
          done

      - name: Run e2e Tests
        run: ./build/main ./build/e2e_test.txt foo